// InsightGenesis CI/CD.
//
// Builds directly in the live checkout at /root/InsightGenesis and reloads
// the root pm2 process, so the controller must run as root (it does) and this
// pipeline must never run concurrently with itself.

pipeline {
  agent any

  options {
    timestamps()
    disableConcurrentBuilds()
    timeout(time: 45, unit: 'MINUTES')
    buildDiscarder(logRotator(numToKeepStr: '30', artifactNumToKeepStr: '10'))
    skipDefaultCheckout(true)
  }

  environment {
    APP_DIR   = '/root/InsightGenesis'
    GIT_CRED  = 'insightgenesis-github'
    PM2_APP   = 'insightgenesis'
    HEALTH_URL= 'http://localhost:5000/'
    // frontend/build is generated by this pipeline and is tracked in git,
    // so it must be excluded from the "uncommitted work" guard below.
    GENERATED = 'frontend/build'
  }

  stages {

    stage('Preflight') {
      steps {
        dir(env.APP_DIR) {
          script {
            // The live tree is also the deploy target. If someone hand-edits
            // source here, a `git pull` would silently discard that work, so
            // refuse to build instead and make the operator commit it.
            def dirty = sh(
              script: '''
                git status --porcelain -- . ':(exclude)frontend/build' ':(exclude)package-lock.json' ':(exclude)package.json'
              ''',
              returnStdout: true
            ).trim()

            if (dirty) {
              error("""\
Refusing to build: ${env.APP_DIR} has uncommitted source changes:

${dirty}

These would be lost by the deploy. Commit them (and push) or stash them, \
then rebuild.""")
            }

            def branch = sh(script: 'git rev-parse --abbrev-ref HEAD', returnStdout: true).trim()
            if (branch != 'main') {
              error("Refusing to build: live checkout is on '${branch}', expected 'main'.")
            }
          }
          sh 'node --version && npm --version && git --version'
        }
      }
    }

    stage('Checkout') {
      steps {
        dir(env.APP_DIR) {
          // Token is injected per-command rather than persisted into
          // .git/config, so the PAT never lands on disk.
          withCredentials([usernamePassword(
              credentialsId: env.GIT_CRED,
              usernameVariable: 'GIT_U',
              passwordVariable: 'GIT_P')]) {
            sh('''
              set -eu
              git remote set-url origin https://github.com/InsightGenesisAI/InsightGenesis.git
              git -c http.extraHeader="Authorization: Basic $(printf '%s:%s' "$GIT_U" "$GIT_P" | base64 -w0)" \
                  fetch --prune origin main
              git checkout -B main
              git reset --hard origin/main
              git log -1 --format='deployed commit: %h %s'
            ''')
          }
        }
      }
    }

    stage('Install') {
      steps {
        dir(env.APP_DIR) {
          sh 'npm install --no-audit --no-fund'
          sh 'npm --prefix frontend install --no-audit --no-fund'
        }
      }
    }

    stage('Build') {
      steps {
        dir(env.APP_DIR) {
          // Runs `tsc --noEmit && vite build`; a type error fails the build
          // before anything is deployed.
          sh 'npm run build'
        }
      }
    }

    stage('Deploy') {
      steps {
        dir(env.APP_DIR) {
          script {
            if (env.BRANCH_NAME != 'main') {
              echo "Not on main, skipping deploy."
              return
            }
            sh '''
              set -eu
              pm2 reload "$PM2_APP" --update-env
              pm2 describe "$PM2_APP" | grep -E "status|restarts|uptime"
            '''
          }
        }
      }
    }

    stage('Health check') {
      steps {
        // Fail loudly if the reloaded process is not actually serving.
        sh '''
          set -eu
          for i in $(seq 1 20); do
            code=$(curl -s -o /dev/null -w '%{http_code}' "$HEALTH_URL" || true)
            if [ "$code" = "200" ]; then
              echo "healthy after ${i} attempt(s): HTTP $code from $HEALTH_URL"
              exit 0
            fi
            echo "attempt ${i}: HTTP ${code:-none}, waiting"
            sleep 3
          done
          echo "app did not become healthy"
          pm2 logs "$PM2_APP" --lines 40 --nostream || true
          exit 1
        '''
      }
    }
  }

  post {
    success {
      if (env.BRANCH_NAME == 'main') {
        echo "Deployed ${env.GIT_COMMIT} to the live pm2 process."
      }
    }
    failure {
      sh 'pm2 describe "${PM2_APP:-insightgenesis}" 2>/dev/null | grep -E "status|restarts" || true'
    }
    always {
      // Archive the fresh build so a rollback can pick an artifact up later.
      // archiveArtifacts reads from the workspace, so stage the tarball there.
      dir(env.APP_DIR) {
        sh 'tar -czf "$WORKSPACE/frontend-build.tgz" frontend/build 2>/dev/null || true'
      }
      archiveArtifacts artifacts: 'frontend-build.tgz', fingerprint: true, allowEmptyArchive: true
    }
  }
}